# Generated by Django 3.2.5 on 2022-10-27 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BOOKED', 'BOOKED'), ('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('CANCELED', 'CANCELED')], default='BOOKED', max_length=15)),
                ('attachment', models.FilePathField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ONETIMEFORM', 'ONETIMEFORM'), ('SUBSCRIPTIONFORM', 'SUBSCRIPTIONFORM')], max_length=20)),
                ('is_assessed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('assessed_date', models.DateTimeField(null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formassessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormAssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(choices=[('CANCER', 'CANCER'), ('ALLERGIES', 'ALLERGIES')], max_length=100)),
                ('question_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('TABLET', 'TABLET'), ('CAPSULES', 'CAPSULES'), ('VACCINE', 'VACCINE')], max_length=50)),
                ('available_quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedVaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('Medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPService.medicine')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPService.country')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescribed_quantity', models.IntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GPService.appointment')),
                ('form_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GPService.formassessment')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPService.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FORMASSESSMENT', 'FORMASSESSMENT'), ('VIDEOASSESSMENT', 'VIDEOASSESSMENT'), ('PRESCRIPTION', 'PRESCRIPTION')], max_length=50)),
                ('created_date', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPService.appointment')),
                ('form_assessment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GPService.formassessment')),
            ],
        ),
        migrations.CreateModel(
            name='FormAssessmentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provided_feedback', models.TextField()),
                ('posted_date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('form_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPService.formassessment')),
            ],
        ),
        migrations.CreateModel(
            name='FormAssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('form_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPService.formassessment')),
                ('form_assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPService.formassessmentquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('starting_time', models.TimeField(default=django.utils.timezone.now)),
                ('ending_time', models.TimeField(default=django.utils.timezone.now)),
                ('is_booked', models.BooleanField(default=False)),
                ('doctor_charge', models.IntegerField(default=1000)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GPService.availability'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
