# Generated by Django 3.2.5 on 2022-11-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
