# Generated by Django 3.2.5 on 2022-12-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
