# Generated by Django 3.2.5 on 2022-11-16 08:57

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='availability',
            name='doctor_charge',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='availability',
            name='ending_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='starting_time',
            field=models.TimeField(),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('starting_time', 'ending_time', 'doctor'), name='unique_appointment_slot'),
        ),
    ]
