# Generated by Django 3.2.5 on 2022-12-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0002_alter_formassessmentfeedback_posted_date'),
        ('GPService', '0002_auto_20221202_1032'),
    ]

    operations = [
    ]
