# Generated by Django 3.2.5 on 2022-11-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0002_alter_medicine_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='available_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
