# Generated by Django 3.2.5 on 2022-11-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0002_auto_20221116_1427'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('patient', 'availability'), name='unique_appointment'),
        ),
    ]
