# Generated by Django 3.2.5 on 2022-12-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0004_auto_20221202_1143'),
        ('GPService', '0005_alter_medicine_name'),
    ]

    operations = [
    ]
