# Generated by Django 3.2.5 on 2022-12-26 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0006_auto_20221226_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(null=True, verbose_name=django.utils.timezone.now),
        ),
    ]
