# Generated by Django 3.2.5 on 2022-12-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0007_auto_20221205_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formassessmentquestion',
            name='question',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
