# Generated by Django 3.2.5 on 2022-12-26 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0007_alter_order_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
