# Generated by Django 3.2.5 on 2022-12-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0008_auto_20221205_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formassessmentquestion',
            old_name='treatment',
            new_name='treatments',
        ),
    ]
