# Generated by Django 3.2.5 on 2022-12-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0008_alter_order_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
