# Generated by Django 3.2.5 on 2022-12-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0012_auto_20221215_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formassessmentquestion',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
