# Generated by Django 3.2.5 on 2023-01-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0013_alter_formassessmentquestion_question'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='formassessmentanswer',
            constraint=models.UniqueConstraint(fields=('form_assessment_question', 'form_assessment'), name='unique_answer_per_question_per_form'),
        ),
    ]
