# Generated by Django 3.2.5 on 2023-01-09 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0007_alter_recommendedvaccine_posted_date'),
        ('GPService', '0013_alter_formassessmentquestion_question'),
    ]

    operations = [
    ]
