# Generated by Django 3.2.5 on 2023-02-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0002_auto_20221201_1402'),
        ('GPService', '0014_formassessmentanswer_unique_answer_per_question_per_form'),
        ('GPService', '0014_merge_20230109_1016'),
    ]

    operations = [
    ]
