# Generated by Django 3.2.5 on 2023-02-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0015_merge_20230209_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formassessmentfeedback',
            name='provided_feedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='GPService.appointment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='form_assessment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='GPService.formassessment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='GPService.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='form_assessment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='GPService.formassessment'),
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicine',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ManyToManyField(related_name='prescriptions', to='GPService.Medicine'),
        ),
    ]
