# Generated by Django 3.2.5 on 2023-02-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0016_auto_20230214_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='GPService.appointment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='form_assessment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='GPService.formassessment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='GPService.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='form_assessment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='GPService.formassessment'),
        ),
    ]
