# Generated by Django 3.2.5 on 2023-02-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0017_auto_20230216_1123'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(check=models.Q(('appointment__isnull', True), ('form_assessment__isnull', True), _connector='OR'), name='one_record_constraint'),
        ),
    ]
