# Generated by Django 3.2.5 on 2023-02-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0018_prescription_one_record_constraint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='medicine',
            new_name='medicines',
        ),
    ]
