# Generated by Django 3.2.5 on 2023-02-23 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0016_auto_20230208_1531'),
        ('GPService', '0019_rename_medicine_prescription_medicines'),
    ]

    operations = [
    ]
