# Generated by Django 3.2.5 on 2023-02-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0020_merge_20230223_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pharmacy_review_status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='prescription',
            name='reason_for_rejection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('FORM_ASSESSMENT', 'FORM_ASSESSMENT'), ('VIDEO_ASSESSMENT', 'VIDEO_ASSESSMENT')], max_length=50),
        ),
    ]
