# Generated by Django 3.2.5 on 2023-03-01 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_pharmacy_id'),
        ('GPService', '0021_auto_20230228_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='pharmacy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='users.pharmacy'),
        ),
    ]
