# Generated by Django 3.2.5 on 2023-06-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0022_prescription_pharmacy'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='availability',
            name='unique_appointment_slot',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='doctor',
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('date', 'starting_time', 'ending_time'), name='unique_appointment_slot'),
        ),
    ]
