# Generated by Django 3.2.5 on 2023-06-14 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_doctor_years_of_experience'),
        ('GPService', '0023_auto_20230614_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.doctor'),
        ),
    ]
