# Generated by Django 3.2.5 on 2023-06-14 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_doctor_years_of_experience'),
        ('GPService', '0024_availability_doctor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='availability',
            name='unique_appointment_slot',
        ),
        migrations.AlterField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.doctor'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('date', 'starting_time', 'ending_time', 'doctor'), name='unique_appointment_slot'),
        ),
    ]
