# Generated by Django 3.2.5 on 2023-06-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0025_auto_20230614_1209'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELED'), _negated=True), fields=('availability',), name='unique_appointment'),
        ),
    ]
