# Generated by Django 3.2.5 on 2023-06-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0026_auto_20230615_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
