# Generated by Django 3.2.5 on 2023-06-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_doctor_years_of_experience'),
        ('GPService', '0027_remove_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.patient'),
        ),
    ]
