# Generated by Django 3.2.5 on 2023-06-16 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_doctor_years_of_experience'),
        ('GPService', '0030_auto_20230616_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='formassessment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_formassessments', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='formassessment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_formassessments', to='users.patient'),
        ),
    ]
