# Generated by Django 3.2.5 on 2023-06-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0031_auto_20230616_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
