# Generated by Django 3.2.5 on 2023-06-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_patient_postal_code'),
        ('GPService', '0031_auto_20230616_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_notifications', to='users.pharmacy')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_notifications', to='GPService.prescription')),
            ],
        ),
    ]
