# Generated by Django 3.2.5 on 2023-06-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0032_pharmacynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacynotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
