# Generated by Django 3.2.5 on 2023-06-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0032_prescription_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
