# Generated by Django 3.2.5 on 2023-06-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_patient_postal_code'),
        ('GPService', '0034_alter_pharmacynotification_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacynotification',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_notifications', to='users.pharmacy'),
        ),
    ]
