# Generated by Django 3.2.5 on 2023-06-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0034_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
