# Generated by Django 3.2.5 on 2023-06-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0035_alter_prescription_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
