# Generated by Django 3.2.5 on 2023-06-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0037_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SHIPPED', 'SHIPPED'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('CREDITCARD', 'CREDITCARD'), ('DEBITCARD', 'DEBITCARD'), ('BANKTRANSFER', 'BANKTRANSFER')], default='BANKTRANSFER', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAYED', 'PAYED'), ('OVERDUE', 'OVERDUE')], default='PENDING', max_length=20),
        ),
    ]
