# Generated by Django 3.2.5 on 2023-06-26 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0038_auto_20230626_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAYED', 'PAYED'), ('OVERDUE', 'OVERDUE')], default='PAYED', max_length=20),
        ),
    ]
