# Generated by Django 3.2.5 on 2023-06-27 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0039_auto_20230626_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice',
        ),
    ]
