# Generated by Django 3.2.5 on 2023-06-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0040_remove_invoice_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CREDITCARD', 'CREDITCARD'), ('DEBITCARD', 'DEBITCARD'), ('BANKTRANSFER', 'BANKTRANSFER')], default='BANKTRANSFER', max_length=20),
        ),
    ]
