# Generated by Django 3.2.5 on 2023-06-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0041_auto_20230628_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'CARD'), ('BANKTRANSFER', 'BANKTRANSFER')], default='BANKTRANSFER', max_length=20),
        ),
    ]
