# Generated by Django 3.2.5 on 2023-06-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0042_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'CARD'), ('BANKTRANSFER', 'BANKTRANSFER')], max_length=20),
        ),
    ]
