# Generated by Django 3.2.5 on 2023-06-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0043_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'CARD'), ('BANKTRANSFER', 'BANKTRANSFER')], default='BANKTRANSFER', max_length=20),
        ),
    ]
