# Generated by Django 3.2.5 on 2023-06-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPService', '0044_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'CARD'), ('BANKTRANSFER', 'BANKTRANSFER')], max_length=20),
        ),
    ]
