# Generated by Django 3.2.5 on 2023-02-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_pharmacy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='postal_code',
            field=models.PositiveIntegerField(),
        ),
    ]
