# Generated by Django 3.2.5 on 2023-02-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230227_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
