# Generated by Django 3.2.5 on 2023-06-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230517_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
