# Generated by Django 3.2.5 on 2023-06-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230620_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='postal_code',
            field=models.PositiveIntegerField(),
        ),
    ]
