# Generated by Django 3.2.5 on 2023-06-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_patient_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
    ]
