# Generated by Django 3.2.5 on 2023-06-21 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_patient_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pharmacy',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy', to='users.pharmacy'),
        ),
    ]
